// <auto-generated />
using System;
using FoodIntake.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodIntake.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918011030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FoodIntake.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SchemeId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FoodIntake.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RemoteClientId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FoodIntake.Domain.ConsumptionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightG")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodRecordId");

                    b.HasIndex("MealSectionId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("FoodIntake.Domain.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataSourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalFoodId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "ExternalFoodId")
                        .IsUnique();

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodIntake.Domain.FoodCategory", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FoodId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodCategories");
                });

            modelBuilder.Entity("FoodIntake.Domain.FoodRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimePointId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TimePointId");

                    b.HasIndex("ProjectId", "RemoteResourceId")
                        .IsUnique();

                    b.ToTable("FoodRecords");
                });

            modelBuilder.Entity("FoodIntake.Domain.LineNutrient", b =>
                {
                    b.Property<int>("ConsumptionLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ConsumptionLineId", "NutrientId");

                    b.HasIndex("NutrientId");

                    b.ToTable("LineNutrients");
                });

            modelBuilder.Entity("FoodIntake.Domain.MealSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MealSections");
                });

            modelBuilder.Entity("FoodIntake.Domain.Nutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("FoodIntake.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FoodIntake.Domain.ProjectClient", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("ProjectClients");
                });

            modelBuilder.Entity("FoodIntake.Domain.Scheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schemes");
                });

            modelBuilder.Entity("FoodIntake.Domain.TimePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("TimePoints");
                });

            modelBuilder.Entity("FoodIntake.Domain.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimePointId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimePointId")
                        .IsUnique();

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("FoodIntake.Domain.Category", b =>
                {
                    b.HasOne("FoodIntake.Domain.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodIntake.Domain.Scheme", "Scheme")
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("FoodIntake.Domain.ConsumptionLine", b =>
                {
                    b.HasOne("FoodIntake.Domain.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.FoodRecord", "FoodRecord")
                        .WithMany()
                        .HasForeignKey("FoodRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.MealSection", "MealSection")
                        .WithMany()
                        .HasForeignKey("MealSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodRecord");

                    b.Navigation("MealSection");
                });

            modelBuilder.Entity("FoodIntake.Domain.FoodCategory", b =>
                {
                    b.HasOne("FoodIntake.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.Food", "Food")
                        .WithMany("Categories")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodIntake.Domain.FoodRecord", b =>
                {
                    b.HasOne("FoodIntake.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.TimePoint", "TimePoint")
                        .WithMany()
                        .HasForeignKey("TimePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TimePoint");
                });

            modelBuilder.Entity("FoodIntake.Domain.LineNutrient", b =>
                {
                    b.HasOne("FoodIntake.Domain.ConsumptionLine", "ConsumptionLine")
                        .WithMany("Nutrients")
                        .HasForeignKey("ConsumptionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionLine");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("FoodIntake.Domain.ProjectClient", b =>
                {
                    b.HasOne("FoodIntake.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodIntake.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FoodIntake.Domain.TimePoint", b =>
                {
                    b.HasOne("FoodIntake.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FoodIntake.Domain.Upload", b =>
                {
                    b.HasOne("FoodIntake.Domain.TimePoint", "TimePoint")
                        .WithMany()
                        .HasForeignKey("TimePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimePoint");
                });

            modelBuilder.Entity("FoodIntake.Domain.ConsumptionLine", b =>
                {
                    b.Navigation("Nutrients");
                });

            modelBuilder.Entity("FoodIntake.Domain.Food", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
